# Vectorization

Vectorization은 기본적으로 for loop들을 제거하는 방법이다. Deep Learning에서는 매우 큰 데이터 셋을 학습시키기 때문에 학습 속도가 매우 중요하다. 매우 큰 데이터 셋을 학습시킬 때 for loop을 사용하게 될 경우, 학습 속도가 매우 느려지게 되므로 Deep Learning에서 Vectorization은 중요한 방법이다. 

In [2]:
import numpy as np
import time

In [9]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version :" + str(1000*(toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000) :
    c += a[i] * b[i]
toc = time.time()

print(c)
print("for-loop :" + str(1000*(toc - tic)) + "ms")

249949.42237280653
Vectorized version :1.9938945770263672ms
249949.42237280443
for-loop :549.7884750366211ms


# Broadcasting

In [4]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [18]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Numpy Vectors

In [29]:
a = np.random.randn(5)
print(a)

[-0.42194369  0.24183688  0.01259779 -0.40465065 -0.76195526]


In [30]:
print(a.shape)

(5,)


In [31]:
print(a.T)

[-0.42194369  0.24183688  0.01259779 -0.40465065 -0.76195526]


In [32]:
print(a.T.shape)

(5,)


In [33]:
print(np.dot(a, a.T))

0.980998232821086


In [34]:
b = np.random.randn(5,1)
print(b)

[[ 0.60595381]
 [-2.37884477]
 [-0.63928629]
 [-0.81568144]
 [ 0.58168391]]


In [36]:
print(b.shape)

(5, 1)


In [35]:
print(b.T)

[[ 0.60595381 -2.37884477 -0.63928629 -0.81568144  0.58168391]]


In [37]:
print(np.dot(b, b.T))

[[ 0.36718002 -1.44147006 -0.38737797 -0.49426528  0.35247358]
 [-1.44147006  5.65890246  1.52076286  1.94037953 -1.38373572]
 [-0.38737797  1.52076286  0.40868697  0.52145397 -0.37186255]
 [-0.49426528  1.94037953  0.52145397  0.66533621 -0.47446877]
 [ 0.35247358 -1.38373572 -0.37186255 -0.47446877  0.33835617]]
